In [3]:
import numpy as np
import time

In [2]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [19]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print(f"Vectorized version: {1000*(toc -tic)}ms")

c = 0
tic = time.time()

for i in range(1000000):
    c += a[i]*b[i]

toc = time.time()

print(c)
print(f"For-loop version: {1000*(toc -tic)}ms")    

250047.25452185847
Vectorized version: 1.1060237884521484ms
250047.25452185472
For-loop version: 366.1010265350342ms


As mentioned in the slides, **for-loop** version is much much **much slower than** the **vectorized** version

Ng: Vectorization: “is basically the art of getting rid of explicit for loops in your code”

In [26]:
# generating random data with numpy

a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(a.dot(a.T))

[ 0.67523466  0.4660695  -1.40292365 -0.04076497  0.55828999]
(5,)
[ 0.67523466  0.4660695  -1.40292365 -0.04076497  0.55828999]
2.9547068821339666


In [28]:
a = np.random.randn(5,1)
print(a) # 5x1 matrix
print(a.T) #1xt matrix


[[ 0.618903  ]
 [-1.50319174]
 [ 1.21265913]
 [ 0.14260117]
 [-1.86363629]]
[[ 0.618903   -1.50319174  1.21265913  0.14260117 -1.86363629]]
